export const STUDENT_REGISTER = "STUDENT_REGISTER";
export const STUDENT_LOGIN = "STUDENT_LOGIN";
export const STUDENT_DETAILS = "STUDENT_DETAILS";


export const NOMINATION_REGISTER = "NOMINATION_REGISTER";
export const NOMINATION_LIST = "NOMINATION_LIST";
export const NOMINATION_DETAILS = "NOMINATION_DETAILS";


export const ADMIN_LOGIN = "ADMIN_LOGIN";

